---
- hosts: localhost
  vars:
    services: ['endlessh','boinc','smokeping','cyberchef','searxng','foldingathome','cadvisor','syncthing','diskover','emby','davos','jackett','jellyfin','lidarr','radarr','sonarr','plex','samba','prowlarr','scrutiny','watchtower','ttrss','zoneminder']
    service_ids:
    timezone: 'America/Chicago'
    admin_username: ""
  tasks: