---
- hosts: localhost
  vars:
    services: ['endlessh','boinc','smokeping','cyberchef','searxng','foldingathome','cadvisor','syncthing','diskover','emby','davos','jackett','jellyfin','lidarr','radarr','sonarr','plex','samba','prowlarr','scrutiny','watchtower','ttrss','zoneminder']
    test: False
    service_ids:
    timezone: 'America/Chicago'
  tasks:
    - name: Create service users
      become: yes
      ansible.builtin.user:
        name: "{{ item }}"
        groups: "docker"
        append: yes
      loop: "{{ services }}"
    - name: Get service uid/gid
      become: yes
      ansible.builtin.getent:
        database: passwd
      register: service_ids
    - name: Write docker-compose templates
      template:
        src: ../../templates/docker-compose/{{ item }}/docker-compose.yml.j2
        dest: "/home/{{ item }}/docker-compose.yml"
      loop: "{{ services }}"
    ## Testing/Removal tasks

    - name: Remove service users
      become: yes
      ansible.builtin.user:
        name: "{{ item }}"
        state: absent
      loop: "{{ services }}"
      when: test
    - name: Remove service directories
      become: yes
      ansible.builtin.file:
        name: "/home/{{ item }}"
        state: absent
      loop: "{{ services }}"
      when: test
    