---
- hosts: localhost
  
#  vars:
#    services: ['cadvisor','librespeed','watchtower','scrutiny','jellyfin','samba']
#    timezone: 'America/Chicago'
#    compose_root: ./
#    admin_user_id: "1000"
#    fileaccess_gid: "1001"
#    librespeed_password: 
  tasks:
    - name: Generate password for librespeed 
      command: openssl rand -hex 16
      register: librespeed_password
    - name: Create services directory and subdirs.
      command: "mkdir -p {{ compose_root}}services/{{ item }}"
      loop: "{{ services }}"
    - name: Write docker-compose templates
      template:
        src: ../templates/docker-compose/{{ item }}/docker-compose.yml.j2
        dest: "{{ compose_root }}services/{{ item }}/docker-compose.yml"
      loop: "{{ services }}"
