---
- hosts: localhost
  vars:
    services: ['endlessh','boinc','smokeping','cyberchef','searxng','foldingathome','cadvisor','syncthing','diskover','emby','davos','jackett','jellyfin','lidarr','radarr','sonarr','plex','samba','prowlarr','scrutiny','watchtower','ttrss','zoneminder']
    service_ids:
    davos_download: /tank/davos
    torrent_blackhole: /tank/stuff/blackhole
    plex_claim: "token"
    timezone: 'America/Chicago'
    admin_username: ""
  tasks:
    - name: Create service directories
      ansible.builtin.file:
        path: "/home/{{ admin_username }}/{{ item }}"
        owner: "{{ admin_username }}"
        group: "{{ admin_username }}"
        state: directory
      loop: "{{ services }}"
    - name: Get service uid/gid
      ansible.builtin.user:
        name: "{{ admin_username }}"
        groups: "docker,fileaccess"
        append: yes
      loop: "{{ services }}"
    - name: Get service uid/gid
      become: yes
      ansible.builtin.getent:
        database: passwd
      register: service_ids
    - name: Write docker-compose templates
      template:
        src: ../../templates/docker-compose/{{ item }}/docker-compose.yml.j2
        dest: "/home/{{ admin_username }}/{{ item }}/docker-compose.yml"
      loop: "{{ services }}"
