---
- hosts: localhost
  vars:
    services: ['endlessh','librespeed','boinc','smokeping','ttrss','cyberchef','searxng']
    test: True
    service_ids:
    timezone: 'America/Chicago'
  tasks:
    - name: Create service users
      become: yes
      ansible.builtin.user:
        name: "{{ item }}"
      loop: "{{ services }}"
    - name: Get service uid/gid
      become: yes
      ansible.builtin.getent:
        database: passwd
      register: service_ids
    - name: Write docker-compose templates
      template:
        src: ../../templates/docker-compose/{{ item }}/docker-compose.yml.j2
        dest: "/home/{{ item }}/docker-compose.yml"
      loop: "{{ services }}"
      
    - name: Start docker-compose for each user
      become: yes
      sudo_user: "{{ item }}"
      command: "ls ~"
      loop: "{{ services }}"
    ## Testing/Removal tasks
    - name: Remove service users
      become: yes
      ansible.builtin.user:
        name: "{{ item }}"
        state: absent
      loop: "{{ services }}"
      when: test
    - name: Remove service directories
      become: yes
      ansible.builtin.file:
        name: "/home/{{ item }}"
        state: absent
      loop: "{{ services }}"
      when: test
    