# Create administrator and service dedicated users as well as access groups for shared files
---
- hosts: localhost
  vars:
    #Set this before run obv
    admin_username: "deathclassic"
    default_dirs: ['src','sbox']
  tasks:
    - name: Create fileaccess group
      become: yes
      ansible.builtin.group:
        name: fileaccess
        state: present
        gid: 1001
    - name: Create admin user
      become: yes
      ansible.builtin.user:
        name: "{{ admin_username }}"
        shell: /bin/zsh
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_file: "/home/{{ admin_username }}/.ssh/id_rsa"
        groups: sudo,docker,fileaccess
      when: admin_username is not undefined
    - name: Create default dirs in home
      become: yes
      ansible.builtin.file:
        path: "/home/{{ admin_username }}/{{ item }}"
        owner: "{{ admin_username }}"
        group: "{{ admin_username }}"
        state: directory
      loop: "{{ default_dirs }}"
    