---
  tasks:
    - name: Read services from services.yml
      include_vars:
        file: services.yml
        name: services
    - name: Stop all services listed in the service.yml file
      command: systemctl stop {{ item }}
      become: yes
      loop: "{{ services }}"
    - name: Navigate to the home directory of the service user
      command: cd /home/{{ item }}
      become: yes
      loop: "{{ services }}"
    - name: Execute docker-compose.yml to cleanup the service from docker
      command: docker-compose down --rmi all --volumes
      become: yes
      loop: "{{ services }}"
