# Clean up docker-compose service volumes, images and networks
---
- hosts: localhost
  vars:
    services: ['endlessh','boinc','smokeping','cyberchef','searxng','foldingathome','cadvisor','syncthing','diskover','emby','davos','jackett','jellyfin','lidarr','radarr','sonarr','plex','samba','prowlarr','scrutiny','watchtower','ttrss','zoneminder']
    admin_username: ""
  tasks:
    tasks:
    - name: Docker-compose kill the services!
      command: docker-compose kill
      become: yes
      become_user: "{{ admin_username }}" 
      args:
        chdir: "/home/{{ admin_username }}/{{ item }} "
      loop: "{{ services }}"
    - name: Docker-compose rm
      command: docker-compose rm -f
      become: yes
      become_user: "{{ admin_username }}" 
      args:
        chdir: "/home/{{ admin_username }}/{{ item }} "
      loop: "{{ services }}"