---
  vars:
    ssh_port: 2222
  tasks:
    - name: Remove old keys
      become: yes
      ansible.builtin.file:
        name: "{{ item }}"
        state: absent
      with_fileglob:
      - "/etc/ssh/ssh_host_*"
    - name: Generate new ssh_host_rsa_key
      become: yes
      command: ssh-keygen -t rsa -b 4096 -f /etc/ssh/ssh_host_rsa_key -N ""
    - name: Generate new ssh_host_ed25519_key
      become: yes
      command: ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N ""
    - name: Remove small Diffie-Hellman moduli
      become: yes
      command: awk '$5 >= 3071' /etc/ssh/moduli > /etc/ssh/moduli.safe && mv /etc/ssh/moduli.safe /etc/ssh/moduli
    - name: Restrict supported key exchange, cipher, and MAC algorithms
      become: yes
      command: echo -e "\\n# Restrict key exchange, cipher, and MAC algorithms, as per sshaudit.com\\n# hardening guide.\\nKexAlgorithms sntrup761x25519-sha512@openssh.com,curve25519-sha256,curve25519-sha256@libssh.org,gss-curve25519-sha256-,diffie-hellman-group16-sha512,gss-group16-sha512-,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha256\\nCiphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr\\nMACs hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128-etm@openssh.com\\nHostKeyAlgorithms ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,sk-ssh-ed25519@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256,rsa-sha2-256-cert-v01@openssh.com" > /etc/ssh/sshd_config.d/ssh-audit_hardening.conf
    - name: Restart ssh service
      become: yes
      ansible.builtin.service:
        name: sshd
        state: restarted
    - name: Install sshaudit
      become: yes
      ansible.builtin.pip:
        name: ssh-audit
        state: present
    - name: UFW allow on new ssh port
      become: yes
      command: "ufw allow {{ ssh_port }}"
    - name: Ensure ssh is listening on port 2222
      become: yes
      ansible.builtin.shell:
        cmd: |
          if ! ss -tuln | grep ':2222'; then
            sed -i 's/#Port 22/Port 2222/g' /etc/ssh/sshd_config
            service ssh restart
          fi
      ignore_errors: yes