# Setup local hosts file with direct dns entries
---
- hosts: localhost
  vars:
  tasks:
  - name: Write NAS local address hosts entry
    become: yes
    lineinfile:
      dest: /etc/hosts
      line: "192.168.1.4 nas.local"
      state: present

