# Install necessary dependencies to get desktop up and running.
- hosts: localhost
  vars:
    tailscale:
    tailscale_login:
    brave_deps: ['apt-transport-https', 'curl']
  tasks:
  - name: Install zfsutils
    become: yes
    ansible.builtin.apt:
      name: zfsutils
      state: present
  - name: Collect tailscale state
    command: tailscale ip -4
    register: tailscale
  - name: Install tailscale
    become: yes
    command: curl -fsSL https://tailscale.com/install.sh | sh
    when: tailscale is undefined
  - name: Start tailscale
    become: yes
    command: sudo tailscale up
    register: tailscale_login
    when: tailscale is undefined
  - name: Install git
    become: yes
    ansible.builtin.apt:
      name: git
      state: present
  - name: Install openssh
    become: yes
    ansible.builtin.apt:
      name: openssh
      state:
  - name: Install zsh
    become: yes
    ansible.builtin.apt:
      name: git
      state: present
  - name: Install docker
    become: yes
    ansible.builtin.apt:
      name: docker
      state: present
  - name: Install docker-compose
    become: yes
    ansible.builtin.apt:
      name: docker-compose
      state: present
  - name: Download docker-slim tarball
    command: curl -L -o ds.tar.gz https://downloads.dockerslim.com/releases/1.38.0/dist_linux.tar.gz
  - name: Extract docker-slim tarball
    command: tar -xvf ds.tar.gz
  - name: Move docker-slim to /usr/local/bin
    become: yes
    command: mv dist_linux/docker-slim /usr/local/bin
  - name: Move docker-slim-sensor to /usr/local/bin
    become: yes
    command: mv dist_linux/docker-slim-sensor /usr/local/bin
  - name: Remove docker-slim artifacts
    command: rm -rf ds.tar.gz dist_linux
  - name: Install Brave browser repos
    become: yes
    command: ../../scripts/add_brave_repos.sh
  - name: Install brave package.
    become: yes
    ansible.builtin.apt:
      name: brave-browser
      state: present
  - name: Install VScode.(x86_64)
    become: yes
    ansible.builtin.apt:
      deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
    when: ansible_architecture == "x86_64"
  - name: Install VScode (arm64)
    become: yes
    ansible.builtin.apt:
      deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-arm64
    when: ansible_architecture == "arm64"
  - name: Install sshfs
    become: yes
    ansible.builtin.apt:
      name: sshfs
      state: present
  