#Playbook to install reverse proxy, vpn and gateway services on a cloud vps.
---
- hosts: all
  become: yes
  tasks:
    - name: Create new partition
      parted:
        device: /dev/sda
        number: 1
        state: present
        flags: lvm
    - name: Format the partition
      filesystem:
        fstype: ext4
        dev: /dev/sda1
    - name: Mount the partition
      mount:
        path: /
        src: /dev/sda1
        fstype: ext4
    - name: Resize the partition
      parted:
        device: /dev/sda
        number: 1
        state: resizepart
        resizefs: yes
        end: 100%