  # Install security hardening and auditing tools
  tasks:
    - name: Install fail2ban
      become: yes
      ansible.builtin.apt:
        name: fail2ban
        state: present
      ignore_errors: yes
    - name: Install rkhunter
      become: yes
      ansible.builtin.apt:
        name: rkhunter
        state: present
      ignore_errors: yes
    - name: Configure rkhunter baseline
      become: yes
      command: rkhunter --propupd
      ignore_errors: yes
    - name: Install osquery (x86_64)
      become: yes
      ansible.builtin.apt:
        deb: https://pkg.osquery.io/deb/osquery_5.5.1-1.linux_amd64.deb
      when: ansible_architecture == "x86_64"
      ignore_errors: yes
    - name: Install osquery (arm64)
      become: yes
      ansible.builtin.apt:
        deb: https://pkg.osquery.io/deb/osquery_5.5.1-1.linux_arm64.deb
      when: ansible_architecture == "arm64"
      ignore_errors: yes
    - name: Write osquery script
      become: yes
      ansible.builtin.copy:
        dest: /opt/osquery/osquery.sh
        content: |
          #!/bin/bash
          osqueryi --json "SELECT * FROM processes;"
        mode: 0755
      ignore_errors: yes
    - name: Install clamav
      become: yes
      ansible.builtin.apt:
        name: clamav
        state: present
      ignore_errors: yes
    - name: Update clamav database
      become: yes
      command: freshclam
      ignore_errors: yes
    - name: Create clam temp infected file quarantine
      become: yes
      ansible.builtin.file:
        path: /var/temp/infected
        state: directory
        owner: root
      ignore_errors: yes
    - name: Install ufw
      become: yes
      ansible.builtin.apt:
        name: ufw
        state: present
      ignore_errors: yes
    - name: Enable ufw
      become: yes
      command: ufw enable
      ignore_errors: yes
    - name: Install trivy repos
      become: yes
      command: ../../scripts/add_trivy_repos.sh
      ignore_errors: yes
    - name: Update apt
      become: yes
      command: sudo apt update
      ignore_errors: yes
    - name: Install trivy package
      become: yes
      ansible.builtin.apt:
        name: trivy
        state: present
    - name: Download ufw-docker
      become: yes
      get_url:
        url: https://github.com/chaifeng/ufw-docker/raw/master/ufw-docker
        dest: /usr/local/bin/ufw-docker
        mode: '0755'

