---
  tasks:
    - name: Read services from services.yml
      include_vars:
        file: /path/to/services.yml
        name: services
    - name: Stop all services listed in the service.yml file
      command: systemctl stop {{ item }}
      become: yes
      loop: "{{ services }}"