# Fire up the docker-compose services!
---
- hosts: localhost
  vars:
    services: ['endlessh','boinc','smokeping','cyberchef','searxng','foldingathome','cadvisor','syncthing','diskover','emby','davos','jackett','jellyfin','lidarr','radarr','sonarr','plex','samba','prowlarr','scrutiny','watchtower','ttrss','zoneminder']
  tasks:
    - name: Docker-compose kill the services!
      command: docker-compose kill
      become: yes
      become_user: "{{ item }}" 
      loop: "{{ services }}"