#This playbook installs everything I need on regolith linux as a workstation desktop. 
---
- hosts: localhost
- import_playbook: install_desktop.yml
- import_playbook: create_users.yml
- import_playbook: install_sectools.yml
- import_playbook: persist_crons.yml