#This playbook installs everything I need on my Network Attached Storage.
- hosts: localhost
- import_playbook: install_nas.yml
- import_playbook: create_users.yml
- import_playbook: install_sectools.yml
- import_playbook: persist_crons.yml
- import_playbook: harden_ssh.yml