  - name: Run apt update and upgrade weekly
    become: yes
    ansible.builtin.cron:
      name: "Apt update and upgrade"
      minute: "0"
      hour: "3"
      weekday: "7"
      user: root
      job: "sudo apt update && sudo apt upgrade -y >/dev/null 2>&1"
    ignore_errors: yes
  - name: Clamscan home daily
    become: yes
    ansible.builtin.cron:
      name: "/home clamscan"
      minute: "0"
      hour: "5"
      user: root
      job: "clamscan --recursive --move=/var/temp/infected --leave-temps=yes --log=/home/homescan.log /home"
    ignore_errors: yes
  - name: Clamscan root weekly
    become: yes
    ansible.builtin.cron:
      name: "/root clamscan"
      minute: "0"
      hour: "1"
      weekday: "7"
      user: root
      job: "clamscan --recursive --move=/var/temp/infected --leave-temps=yes --log=/root/rootscan.log /"
    ignore_errors: yes
  - name: Update clamd daily
    become: yes
    ansible.builtin.cron:
      name: "Update clamd"
      minute: "15"
      hour: "3"
      user: root
      job: "freshclam -d >/dev/null 2>&1"
    ignore_errors: yes
  - name: Update rkhunter 3 days a week
    become: yes
    ansible.builtin.cron:
      name: "Update rkhunter"
      minute: "30"
      hour: "3"
      weekday: "2,4,6"
      user: root
      job: "/usr/bin/rkhunter --cronjob --update --quiet"
    ignore_errors: yes
  - name: Update docker images weekly
    become: yes
    ansible.builtin.cron:
      name: "Update docker images"
      minute: "45"
      hour: "3"
      weekday: "7"
      user: root
      job: "docker image prune -a -f"
    ignore_errors: yes
      hour: "date docker images"
      minute: "become: yes
    ansible.builtin.cron:
      name: "Update rkhunter"
      minute: "10"
      hour: "4"
      weekday: "1,3,5"
      user: root
      job: "/usr/bin/rkhunter --cronjob --update --quiet"
    ignore_errors: yes
  - name: Update tailscale weekly
    become: yes
    ansible.builtin.cron:
      name: "Update tailscale"
      minute: "12"
      hour: "6"
      weekday: "7"
      user: root
      job: "apt update && apt install tailscale"
    ignore_errors: yes
  - name: Run a weekly docker system prune
    become: yes
    ansible.builtin.cron:
      name: "Docker system prune"
      minute: "22"
      hour: "5"
      weekday: "7"
      user: root
      job: "docker system prune -a -f --volumes"
    ignore_errors: yes
  