---
  tasks:
    - name: Read services.yml
      include_vars:
        file: services.yml
        name: services
    - name: Create and start systemd service for each service
      block:
        - name: Create systemd service file
          copy:
            dest: "/etc/systemd/system/{{ item.name }}.service"
            content: |
              [Unit]
              Description={{ item.name }} service
              After=network.target

              [Service]
              Type=simple
              User={{ item.name }}
              ExecStart=/usr/local/bin/docker-compose -f /home/{{ item.name }}/docker-compose.yml up
              Restart=on-failure

              [Install]
              WantedBy=multi-user.target
          become: yes
        - name: Enable systemd service
          systemd:
            name: "{{ item.name }}"
            enabled: yes
            state: restarted
          become: yes
      loop: "{{ services }}"