# Fire up the docker-compose services!
---
- hosts: localhost
  vars:
    services: ['endlessh','boinc','smokeping','cyberchef','searxng','foldingathome','cadvisor','syncthing','diskover','emby','davos','jackett','jellyfin','lidarr','radarr','sonarr','plex','samba','prowlarr','scrutiny','watchtower','ttrss','zoneminder']
    admin_username: ""
  tasks:
    - name: Docker-compose up the services!
      command: "docker-compose /home/{{ admin_username }}/{{ item }} up -d"
      become: yes
      become_user: "{{ admin_username }}" 
      loop: "{{ services }}"