# Install necessary dependencies to get NAS up and running.
- hosts: localhost
  vars:
    tailscale:
    tailscale_login:
  tasks:
  - name: Install tailscale repos
    become: yes
    command: ../../scripts/add_tailscale_repos.sh
  - name: Install tailscale package
    become: yes
    ansible.builtin.apt:
      name: tailscale
      state: present

  