---
- hosts: all
  tasks:
    - name: Read services.yml
      become: yes
      include_vars:
        file: services.yml
    - name: Create fileaccess group
      become: yes
      group:
        name: fileaccess
        state: present
    - name: Create users from services list and add to fileaccess group if fileaccess is true
      become: yes
      user:
        name: "{{ item.name }}"
        state: present
        groups: "{{ 'fileaccess' if item.fileaccess else '' }}"
      with_items: "{{ services }}"
    - name: Add users to docker group
      become: yes
      user:
        name: "{{ item.name }}"
        groups: docker
        append: yes
      with_items: "{{ services }}"
