# Configure zfs storage arrays.
---
- hosts: localhost
  vars:
    tank:
    mainarray:
  tasks:
  - name: Check if tank array is imported.
    become: yes
    command: zpool status tank
    register: tank
  - name: Check if mainarray is imported
    command: zpool status mainarray
    become: yes
    register: mainarray
  - name: Import mainarray zfs pool
    become: yes
    command: zpool import mainarray
    when: mainarray is undefined
  - name: Import tank zfs pool
    become: yes
    command: zpool import tank
    when: tank is undefined
