---
- name: Setup ZFS arrays
  hosts: all
  vars:
    tank: tank
    mainarray: mainarray
  tasks:
    - name: Check if zfs is installed
      become: yes
      command: zfs --version
      register: zfs_installed_result
      ignore_errors: yes
    - name: Set zfs_installed
      set_fact:
        zfs_installed: "{{ zfs_installed_result | default({'rc': 1}) }}"
    - name: Check if zfs arrays exist
      become: yes
      command: zpool list | grep {{ item }}
      register: zfs_array_exists_result
      ignore_errors: yes
      with_items:
        - "{{ tank }}"
        - "{{ mainarray }}"
    - name: Set zfs_array_exists
      set_fact:
        zfs_array_exists: "{{ zfs_array_exists_result | default({'rc': 1}) }}"
    - name: Import zfs arrays
      become: yes
      command: zpool import {{ item }}
      with_items:
        - "{{ tank }}"
        - "{{ mainarray }}"
      ignore_errors: yes
    - name: Check if docker is installed
      command: docker --version
      register: docker_installed
      ignore_errors: yes
    - name: Configure docker to use zfs
      block:
        - name: Update docker-daemon.json
          become: yes
          copy:
            dest: /etc/docker/daemon.json
            content: |
              {
                "storage-driver": "zfs"
              }
        - name: Create zfs dataset for docker volumes
          become: yes
          command: zfs create {{ tank }}/docker-volumes
        - name: Configure docker to use zfs dataset
          become: yes
          command: docker volume create -d local -o type=zfs -o device={{ tank }}/docker-volumes docker-volumes

