---
vars:
  services:  ['endlessh','boinc','smokeping','cyberchef','searxng','foldingathome','cadvisor','syncthing','diskover','emby','davos','jackett','jellyfin','lidarr','radarr','sonarr','plex','samba','prowlarr','scrutiny','watchtower','ttrss','zoneminder']
  timezone: 'America/Chicago'
  compose_root: ./
  admin_user_id: "1000"
  fileaccess_gid: "1001"
  librespeed_password: 