---
tasks:
  - name: Install zfsutils
    become: yes
    ansible.builtin.apt:
      name: zfsutils
      state: present
  - name: Import mainarray zfs pool
    become: yes
    command: zpool import mainarray
  - name: Import tank zfs pool
    become: yes
    command: zpool import tank
  

