---
- hosts: localhost
  vars:
    tank:
    mainarray:
    tailscale:
    tailscale_login:
    docker_zfs_present:
  tasks:
  - name: Install zfsutils
    become: yes
    ansible.builtin.apt:
      name: zfsutils
      state: present
  - name: Check if tank array is imported.
    become: yes
    command: zpool status tank
    register: tank
  - name: Check if mainarray is imported
    command: zpool status mainarray
    become: yes
    register: mainarray
  - name: Import mainarray zfs pool
    become: yes
    command: zpool import mainarray
    when: mainarray is undefined
  - name: Import tank zfs pool
    become: yes
    command: zpool import tank
    when: tank is undefined
  - name: Collect tailscale state
    command: tailscale ip -4
    register: tailscale
  - name: Install tailscale
    become: yes
    command: curl -fsSL https://tailscale.com/install.sh | sh
    when: tailscale is undefined
  - name: Start tailscale
    become: yes
    command: sudo tailscale up
    register: tailscale_login
    when: tailscale is undefined
  - name: Make sure fileaccess group exists
    group:
      name: fileaccess
      state: present
  - name: Install docker
    become: yes
    ansible.builtin.apt:
      name: docker
      state: present
  - name: Install docker-compose
    become: yes
    ansible.builtin.apt:
      name: docker-compose
      state: 
  - name: Write docker daemon config file
    template:
      src: ../templates/configs/docker/daemon.json.j2
      dest: /etc/docker/daemon.json
  - name: Write ts login link to file
    command: echo { tailscale_login } > tslogin
    when: tailscale is undefined
  - name: Install sshfs
    become: yes
    ansible.builtin.apt:
      name: sshfs
      state: present

    